"""Markdown reporter (good for `gh issue comment` or PR comments)."""

from __future__ import annotations

from dns_healthcheck.result import RunReport, Severity

_BADGE = {
    Severity.INFO: "🟢",
    Severity.NOTICE: "🔵",
    Severity.WARNING: "🟡",
    Severity.ERROR: "🔴",
    Severity.CRITICAL: "⛔",
}


def render_markdown(report: RunReport) -> str:
    sm = report.summary
    lines: list[str] = []
    lines.append(f"# DNS health report — `{report.domain}`")
    lines.append("")
    lines.append(
        f"_profile_ **{report.profile}**  ·  "
        f"_runtime_ **{report.duration_ms} ms**  ·  "
        f"_overall_ **{report.severity.label}**"
    )
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for level in (Severity.CRITICAL, Severity.ERROR, Severity.WARNING, Severity.NOTICE, Severity.INFO):
        lines.append(f"| {level.label} | {sm.get(level.label, 0)} |")
    lines.append(f"| Skipped | {sm['skipped']} |")
    lines.append(f"| Errored | {sm['errored']} |")
    lines.append("")

    by_cat: dict[str, list] = {}
    for r in report.results:
        by_cat.setdefault(r.category, []).append(r)

    for category in sorted(by_cat):
        lines.append(f"## {category.upper()}")
        lines.append("")
        lines.append("| Check | Severity | Findings |")
        lines.append("|---|---|---|")
        for r in by_cat[category]:
            badge = _BADGE.get(r.severity, "")
            sev = r.severity.label if not r.skipped else "SKIP"
            if r.error:
                fmsg = f"⚠️ execution error: {r.error}"
            elif r.skipped:
                fmsg = r.skip_reason or "skipped"
            elif not r.findings:
                fmsg = "ok"
            else:
                fmsg = "<br>".join(
                    f"`{f.severity.label}` {f.message}" + (f" _({f.ns})_" if f.ns else "") for f in r.findings
                )
            lines.append(f"| **{r.check_id}** {r.name} | {badge} {sev} | {fmsg} |")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [dns-healthcheck](https://github.com/Zv1r/dns-healthcheck)_")
    return "\n".join(lines)
